### ISSUE TITLE
Composer branch alias for development

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/booboo#14]
Can you add one something like [this](https://github.com/thephpleague/event/blob/master/composer.json#L32)?

**Comment by brandonsavage** [comment]
What is the value of doing this?

**Comment by sagikazarmark** [comment]
You can rely on a development version which is about to become stable. Makes sense when you start developing something, which depends on something else which itself is still under development (like a new feature introduced without a new release).

It indicates what the next release will be
