### ISSUE TITLE
JsonFormatter outputs invalid JSON with multiple errors

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/booboo#22]
When multiple errors are triggered within the context of a single page, the output renders as:

```json
{"message": "..."}{"message": "..."}
```

This is obviously invalid JSON and will not validate or convert properly. Expected output could be:

```json
{"errors": [{"message": "..."}, {"message": "..."}]}
```

While it is not entirely obvious to me how this would be implemented, some kind of handler "before" and "after" method should make it possible to break it up as:

```php
$before = '{"errors": [';
$after = ']}';
```

**Comment by brandonsavage** [comment]
The way that BooBoo works, it handles each error individually. I recommend using the blocking feature built into the runner:

```
$booboo = new Runner();
$booboo->treatErrorsAsExceptions(true);
```
