### ISSUE TITLE
Hints adding booboo for Laravel 5

### ISSUE THREAD

**Issue by subdesign** [thephpleague/booboo#23]
Any hints implementing booboo into Laravel 5's exception handling system?

**Comment by brandonsavage** [comment]
I'll have to look into how the Laravel system works. Unless @taylorotwell
wants to take a look.

**Comment by taylorotwell** [comment]
In the `Illuminate\Foundation\Http\Kernel` class there is an array of "bootstrapper" classes that boot the framework:

```
	/**
	 * The bootstrap classes for the application.
	 *
	 * @var array
	 */
	protected $bootstrappers = [
		'Illuminate\Foundation\Bootstrap\DetectEnvironment',
		'Illuminate\Foundation\Bootstrap\LoadConfiguration',
		'Illuminate\Foundation\Bootstrap\ConfigureLogging',
		'Illuminate\Foundation\Bootstrap\HandleExceptions',
		'Illuminate\Foundation\Bootstrap\RegisterFacades',
		'Illuminate\Foundation\Bootstrap\RegisterProviders',
		'Illuminate\Foundation\Bootstrap\BootProviders',
	];
```

You will want to override the `Illuminate\Foundation\Bootstrap\HandleExceptions` bootstrapper and can configure BooBoo there. You can override it by replacing this `$bootstrappers` array on your own `App\Http\Kernel` class.

**Comment by subdesign** [comment]
thank you
