### ISSUE TITLE
Figure out why CodeClimate shows only a 60% code coverage amount

### ISSUE THREAD

**Issue by brandonsavage** [thephpleague/booboo#25]
PHPUnit shows an 83% code coverage.

**Comment by potherca** [comment]
This seems to be solved somehow, judging from the [coverage page](https://codeclimate.com/github/thephpleague/booboo/coverage) and coverage badge: [![Test Coverage](https://codeclimate.com/github/thephpleague/booboo/badges/coverage.svg)](https://codeclimate.com/github/thephpleague/booboo/coverage)

(Unless, of course, the actual coverage is now higher than the mentioned 83.45% percent).

**Comment by brandonsavage** [comment]
This appears to have resolved itself.
