### ISSUE TITLE
exceptionHandler doesn't return 500 status when displaying errors

### ISSUE THREAD

**Issue by nebulousGirl** [thephpleague/booboo#37]
Is it by design to mimic how PHP behaves or can I submit a pull request to add the 500 status header when display_errors is set to true?

My main problem with the actual implementation is when I make Ajax request I get a 200 status header even though the request crashed.

If it's by design, should I make my own formatter to add the status header, or is there a better way?

**Comment by quintanilhar** [comment]
I have the same problem, I agree with @nebulousGirl that all responses should be 500 when some error occours, in my case the CDN Service cached an error page because it was 200.

**Comment by shadowhand** [comment]
According to [the code](https://github.com/thephpleague/booboo/blob/309e9b28cd1299b7ff07e8b35f68b96d882b1d5f/src/Runner.php#L145) a 500 error is rendered when `fatalErrors` happen.
