### ISSUE TITLE
CLI not working?

### ISSUE THREAD

**Issue by HeathNaylor** [thephpleague/booboo#38]
Pretty straight forward implementation, I have BooBoo being brought in via composer, I push the formatter and register the instance. I kick off an infinite loop and immediately throw an exception. In my terminal I run `php index.php` and the process immediately exits, I am not presented with any visual output. Am I missing something?

```
<?php

// Autoload packages
require __DIR__ . '/vendor/autoload.php';

$runner = new League\BooBoo\Runner();
$runner->pushFormatter(new \League\BooBoo\Formatter\CommandLineFormatter());
$runner->register();

// Kick off infinite loop
while(true) {
    throw new Exception('a');
}

```

**Comment by brandonsavage** [comment]
Hi Heath,

I used your code to try and reproduce this issue and was unsuccessful. Can you let me know what version of PHP you're running? Thanks!

**Comment by brandonsavage** [comment]
Closing for lack of response.
