### ISSUE TITLE
Could we please have a tagged release for b43a29b6

### ISSUE THREAD

**Issue by salcode** [thephpleague/booboo#45]
Firstly, thank you for this project.  BooBoo has been a big help in the projects I work on.

I was using release `1.0.0` but based on some of the more recent activity, I started using the `master` branch ( which is always a risky idea 😀  ).

With 521257a a break change was introduced to the `master` branch.

Would you please tag a release (e.g. `1.1.0`) for b43a29b6 (i.e. just before the recent breaking changes)?

I can pin the requirement to the specific commit, which I'm doing right now, but I'd love to be able to target a version instead.

Thanks again for all you put into this project and for allowing us to benefit from it.

**Comment by GaryJones** [comment]
A tag for after the breaking changes would also be good if everything else looks peachy.

**Comment by frankdejonge** [comment]
@brandonsavage want me to look into this for you? I could tag the release.

**Comment by brandonsavage** [comment]
I'll need to look back and see exactly where the breaking change occurred. There's a change of Runner -> BooBoo which is breaking and was tagged in v2. I'll see if I can get something put together.

**Comment by brandonsavage** [comment]
This is now tagged 1.1.0. Sorry it took so long!
